[project]
name = "peakanalyzer-scripts"
version = "0.1.0"
description = "质谱数据峰分析工具"
authors = ["PeakAnalyzer Team"]
readme = "README"
requires-python = ">=3.10"

[project.dependencies]
streamlit = ">=1.28.0"
numpy = ">=1.24.0"
scipy = ">=1.11.0"
pandas = ">=2.0.0"
plotly = ">=5.17.0"
openpyxl = ">=3.1.0"
maturin = ">=1.0.0"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "peakanalyzer_scripts"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]
